import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>La web de Juan Flores</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-black h-screen flex items-center justify-center flex-col">
        <h1 className="font-semibold text-5xl text-white">Juan Flores</h1>
        <p className="font-semibold text-xl text-white">
          Realizador Audiovisual
        </p>
      </div>
    </>
  );
}
